########################################################################################################################
## This file was generated by installing a NuGet package.
##
## NuGet Package:   Kwality.CodeStyle
##
## Changes to this file may cause incorrect behavior and will be lost when the file is generated again.
########################################################################################################################

<#
    .SYNOPSIS
        Build a single .NET project / .NET Solution.

    .DESCRIPTION
        Build a single .NET project / .NET Solution.
        Before the build is executed, a `dotnet clean` is executed.
        The `dotnet build` uses the `--no-incremental` flag.

    .PARAMETER Path
        The path to the .NET Project / .NET Solution file to build.

    .PARAMETER CIBuild
        Run a CI (Continuous Integration) build.
        This will treat all warnings as errors.
#>
param(
    [Parameter(Mandatory = $true)]
    [String]
    $Path,

    [Parameter(Mandatory = $false)]
    [switch]
    $CIBuild
)

# Terminate the PowerShell script if the path to the .NET Project / .NET Solution is NOT found.
If (-Not $(Test-Path $Path)) {
    Write-Host ("Count not find the path ``" + $Path + "``.") -ForegroundColor Red

    Exit
}

# Clean the output directory.
dotnet clean $Path

# Build the .NET Project / .NET Solution.
# When the `CIBuild` flag is passed, a CI (Continuous Integration) build is executed.
# This will treat warnings as errors.
If ($CIBuild) {
    dotnet build $InputFullFilePath --no-incremental --property:CIBuild=true
}
Else {
    dotnet build $InputFullFilePath --no-incremental
}
