########################################################################################################################
## This file was generated by installing a NuGet package.
##
## NuGet Package:   Kwality.CodeStyle
##
## Changes to this file may cause incorrect behavior and will be lost when the file is generated again.
########################################################################################################################

<#
    .SYNOPSIS
        Calculate the code coverage of a .NET Project.

    .DESCRIPTION
        Install JetBrains DotCover CLI (https://www.jetbrains.com/dotcover/) and calculate the code coverage of a .NET
        project.

    .PARAMETER Path
        The path to the .NET Project file for which to calculate the code coverage.
#>
param(
    [Parameter(Mandatory = $true)]
    [String]
    $Path
)

# Store the current working directory.
$cwd = Get-Location

# Terminate the PowerShell script if the path to the .NET Solution is NOT found.
If (-Not $(Test-Path $Path)) {
    Write-Host ("Count not find the path ``" + $Path + "``.") -ForegroundColor Red

    Exit
}

try {
    # Create the `.\.Kwality.CodeStyle\dotnet-tools\` folder if it does NOT yet exist.
    If (-Not $(Test-Path ".\.Kwality.CodeStyle\dotnet-tools\")) {
        New-Item ".\.Kwality.CodeStyle\dotnet-tools\" -ItemType Directory
    }

    # Install the .NET Tool `JetBrains.dotCover.CommandLineTools`.
    Set-Location ".\.Kwality.CodeStyle\dotnet-tools\"
    dotnet new tool-manifest --force
    dotnet tool install JetBrains.dotCover.GlobalTool --version 2023.1.0

    # Calculate the code coverage.
    dotnet clean $(Join-Path $cwd $Path -Resolve)
    dotnet build $(Join-Path $cwd $Path -Resolve) --no-incremental
    dotnet tool run dotnet-dotcover test $(Join-Path $cwd $Path -Resolve) --no-build --dcReportType=HTML --dcAttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute
    Invoke-Item dotCover.Output.html
}
finally {
    Set-Location $cwd
}
