########################################################################################################################
## This file was generated by installing a NuGet package.
##
## NuGet Package:   Kwality.CodeStyle
##
## Changes to this file may cause incorrect behavior and will be lost when the file is generated again.
########################################################################################################################

<#
    .SYNOPSIS
        Format a .NET Solution.

    .DESCRIPTION
        Install JetBrains ReSharper CLI (https://www.jetbrains.com/help/resharper/ReSharper_Command_Line_Tools.html) and
        format the .NET Solution.

    .PARAMETER Path
        The path to the .NET Solution file to format.
#>
param(
    [Parameter(Mandatory = $true)]
    [String]
    $Path
)

# Store the current working directory.
$cwd = Get-Location

# Terminate the PowerShell script if the path to the .NET Solution is NOT found.
If (-Not $(Test-Path $Path)) {
    Write-Host ("Count not find the path ``" + $Path + "``.") -ForegroundColor Red

    Exit
}

try {
    # Create the `.\.Kwality.CodeStyle\dotnet-tools\` folder if it does NOT yet exist.
    If (-Not $(Test-Path ".\.Kwality.CodeStyle\dotnet-tools\")) {
        New-Item ".\.Kwality.CodeStyle\dotnet-tools\" -ItemType Directory
    }

    # Install the .NET Tool `JetBrains.ReSharper.GlobalTools`.
    Set-Location ".\.Kwality.CodeStyle\dotnet-tools\"
    dotnet new tool-manifest --force
    dotnet tool install JetBrains.ReSharper.GlobalTools --version 2022.3.2

    # Format the .NET Solution.
    dotnet tool run jb cleanupcode --include="**/*.cs" --no-buildin-settings $(Join-Path $cwd $Path -Resolve)
}
finally {
    Set-Location $cwd
}
