########################################################################################################################
## This file was generated by installing a NuGet package.
##
## NuGet Package:   Kwality.CodeStyle
##
## Changes to this file may cause incorrect behavior and will be lost when the file is generated again.
########################################################################################################################

<#
    .SYNOPSIS
        Use DotNet Stryker and perform mutation testing.

    .DESCRIPTION
        Install DotNet Stryker (https://stryker-mutator.io/) and mutate a .NET Project to get insights into the quality 
        of your test suite.

    .PARAMETER TestProjectFilePath
        The path to the .NET Test Project file.

    .PARAMETER ProjectFilePath
        The path to the .NET Project file.

    .PARAMETER OpenReport
        Open the report once the mutation has finished.
#>
param(
    [Parameter(Mandatory = $true)]
    [String]
    $TestProjectFilePath,

    [Parameter(Mandatory = $true)]
    [String]
    $ProjectFilePath,

    [Parameter(Mandatory = $false)]
    [Switch]
    $OpenReport
)

# Store the current working directory.
$cwd = Get-Location

try {
    # Create the `.\.Kwality.CodeStyle\dotnet-tools\` folder if it does NOT yet exist.
    If (-Not $(Test-Path ".\.Kwality.CodeStyle\dotnet-tools\")) {
        New-Item ".\.Kwality.CodeStyle\dotnet-tools\" -ItemType Directory
    }

    # Install the .NET Tool `.NET Stryker`.
    Set-Location ".\.Kwality.CodeStyle\dotnet-tools\"
    dotnet new tool-manifest --force
    dotnet tool install dotnet-stryker --version 3.6.1

    # Terminate the PowerShell script if the path to the .NET Test Project is NOT found.
    If (-Not $(Test-Path $(Join-Path $cwd $TestProjectFilePath))) {
        Write-Host ("Count not find the path ``" + $TestProjectFilePath + "``.") -ForegroundColor Red

        Exit
    }

    # Terminate the PowerShell script if the path to the .NET Project is NOT found.
    If (-Not $(Test-Path $(Join-Path $cwd $ProjectFilePath))) {
        Write-Host ("Count not find the path ``" + $ProjectFilePath + "``.") -ForegroundColor Red

        Exit
    }

    If ($OpenReport) {
        dotnet tool run dotnet-stryker --test-project $(Join-Path $cwd $TestProjectFilePath -Resolve) --project $(Join-Path $cwd $ProjectFilePath -Resolve) --output StrykerOutput --open-report
    }
    Else {
        dotnet tool run dotnet-stryker --test-project $(Join-Path $cwd $TestProjectFilePath -Resolve) --project $(Join-Path $cwd $ProjectFilePath -Resolve) --output StrykerOutput
    }
}
finally {
    Set-Location $cwd
}
