# ======================================================================================================================
# == LICENSE:       Copyright (c) 2023 Kevin De Coninck
# ==
# ==                Permission is hereby granted, free of charge, to any person
# ==                obtaining a copy of this software and associated documentation
# ==                files (the "Software"), to deal in the Software without
# ==                restriction, including without limitation the rights to use,
# ==                copy, modify, merge, publish, distribute, sublicense, and/or sell
# ==                copies of the Software, and to permit persons to whom the
# ==                Software is furnished to do so, subject to the following
# ==                conditions:
# ==
# ==                The above copyright notice and this permission notice shall be
# ==                included in all copies or substantial portions of the Software.
# ==
# ==                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# ==                EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# ==                OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# ==                NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# ==                HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# ==                WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# ==                FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# ==                OTHER DEALINGS IN THE SOFTWARE.
# ======================================================================================================================

# Common information for the Github workflow.
name: Publish on NuGet
run-name: Publish on NuGet

# Information to determine the conditions under which we want to run this Github workflow.
on:
  push:
    branches:
      - main
    paths:
      - app/Kwality.CodeStyle/**

# Defines the jobs that are executed when this Github workflow is executed.
jobs:

  # Publish on NuGet.
  publish:
    name: Package & release on NuGet.
    runs-on: ubuntu-latest
    steps:
    - name: GIT Clone.
      uses: actions/checkout@v3.3.0

    - name: Setup .NET SDK (7.0.200).
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '7.0.200'

    - name: Build (Kwality.CodeStyle).
      run: dotnet build -c Release app/Kwality.CodeStyle/Kwality.CodeStyle.csproj

    - name: Create NuGet package (Release).
      run: dotnet pack -c Release --no-build app/Kwality.CodeStyle/Kwality.CodeStyle.csproj --output .

    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
